### ISSUE TITLE
New versions don't build properly when included as npm dependency 

### ISSUE THREAD

**Issue by eezcjkr** [parsec-labs/parsec-lib#16]
Newer versions of this package (0.11.0 works, 0.14.0 doesn't), when included as a dependency in package.json and after running npm install, do not contain the dist folder and as such the module cannot be loaded by node.

**Comment by sunify** [comment]
Very interesting why it happens, but 0.14.0 contains dist folder

https://unpkg.com/parsec-lib@0.14.0/dist

**Comment by sunify** [comment]
Would be cool if you will investigate it a bit

**Comment by eezcjkr** [comment]
Will do. Probably something local for me, but if I npm install parsec-lib (the newer versions), when I cd into node_modules/parsec-lib, the dist folder is missing.
