### ISSUE TITLE
[bounty 7] remove pos and and proof from block signature

### ISSUE THREAD

**Issue by johannbarbie** [parsec-labs/parsec-lib#2]
now the `proof(txData, pos, proof) {}` function in `block.js` takes 2 inputs that can be calculated
1. try to find txData in block data
2. deduce position and proof automatically
3. reduce signature to `proof(txData)`

**Comment by sunify** [comment]
I'll look at it

**Comment by johannbarbie** [comment]
@sunify as i understand this is dependent on completion of https://github.com/parsec-labs/parsec-lib/issues/1
