### ISSUE TITLE
color overflow is not detected

### ISSUE THREAD

**Issue by johannbarbie** [parsec-labs/parsec-lib#20]
## Observation:

`const color = 2 ** 16 + 1;` produces:

<img width="798" alt="screen shot 2018-09-05 at 2 13 23 pm" src="https://user-images.githubusercontent.com/659301/45092521-f523e500-b115-11e8-837a-a152cd1a898b.png">

## Expectation:

Error when constructing tx.

**Comment by sunify** [comment]
🤦‍♂️
